diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.name=aecesr
user.email=1725942140@qq.com
http.sslverify=false
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.main.url=https://github.com/aecesr/boot-quickstart.git
remote.main.fetch=+refs/heads/*:refs/remotes/main/*
remote.origin.url=https://github.com/aecesr/boot-learning.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
