server:
  port: 9090

logging:
  level:
    root: info
    com.chl.boot.log.controller: debug
  file:
    name: D:\桌面\logs\my-log.log
  logback:
    rollingpolicy:
      max-file-size: 1MB
      max-history:7
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger : %msg%n'